version: '3.8'

services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      - AUTH_API_ADDRESS=http://auth-api:8000
      - TODOS_API_ADDRESS=http://todos-api:8082

networks:
  app-network:
    driver: bridge
