version: '3.8'

services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8080:8080"

networks:
  app-network:
    driver: bridge
