version: '3.8'

services:
    
  todos-api:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8082:8082"
    environment:
      - JWT_SECRET=PRFT
      - TODO_API_PORT=8082
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel

networks:
  app-network:
    driver: bridge