version: '3.8'

services:
    
  todos-api:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8082:8082"

networks:
  app-network:
    driver: bridge