services:

  redis:
    image: redis:7.0
    networks:
      - app-network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  zipkin:
    image: openzipkin/zipkin
    networks:
      - app-network
    ports:
      - "9411:9411"

  auth-api:
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      - APP_CONFIG_CONNECTION_STRING=${APPCONFIG_CONNECTION_STRING}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      - APP_CONFIG_CONNECTION_STRING=${APPCONFIG_CONNECTION_STRING}

  log-message-processor:
    build:
      context: ./log-message-processor
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - APP_CONFIG_CONNECTION_STRING=${APPCONFIG_CONNECTION_STRING}

  todos-api:
    build:
      context: ./todos-api
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8082:8082"
    environment:
      - APP_CONFIG_CONNECTION_STRING=${APPCONFIG_CONNECTION_STRING}

  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8083:8083"
    environment:
      - APP_CONFIG_CONNECTION_STRING=${APPCONFIG_CONNECTION_STRING}

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: