version: '3.8'

services:
  auth-api:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8000:8000"

networks:
  app-network:
    driver: bridge
  