version: '3.8'

services:

  log-message-processor:
    build:
      context: ./log-message-processor
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge