name: Frontend CI

on:
  push:
    branches:
      - feat/external_configuration_store
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for Frontend
        run: |
          docker build -t frontend ./frontend

      - name: Test Docker image
        run: |
          docker run --rm frontend

      - name: Add VM ip to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      - name: SSH with username and password
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} "echo 'SSH connection successful'"

      - name: Move to repo directory and pull latest changes
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} "cd /opt/microservice-app-example && git config --global --add safe.directory /opt/microservice-app-example && sudo git pull"

      - name: Run docker compose up to update the container
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} "cd /opt/microservice-app-example && cd frontend && sudo docker-compose up -d --build --force-recreate"
